apiVersion: v1
kind: LimitRange
metadata:
  name: set-limits-cpu
  namespace: robot-shop
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 5Gi
    defaultRequest: # this section defines default requests
      cpu: 256m
      memory: 2Gi
    min:  # max and min define the limit range
      cpu: 100m
      memory: 1Gi
    max:
      cpu: "1"
      memory: 3Gi
    type: Container
    
