apiVersion: v1
kind: LimitRange
metadata:
  name: set-limits-cpu
  namespace: robot-shop
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
    defaultRequest: # this section defines default requests
      cpu: 256m
    min:  # max and min define the limit range
      cpu: 100m
    max:
      cpu: "1"
    type: Container
    
