apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fstype: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
