apiVersion: v1
kind: ResourceQuota
metadata:
  name: configure-cpu-memory-quota
  namespace: robot-shop
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 3Gi
